### ISSUE TITLE
add a shader selection (mii rendering styles) to render tab on make your own render

### ISSUE THREAD

**Issue by Rubiidev-IPad** [datkat21/mii-maker.ts#7]
simple, doesn't even need a desc.

**Comment by datkat21** [comment]
If you mean the option to select shader from options like wii u/switch/miitomo, this will be added in the update that i have been working on for almost a month now that also will add all the wii u poses and stuff :)

**Comment by poasterz** [comment]
I know this is completed but maybe there should be a menu to swap render-types (E.g, Wii U (Blinn) to Wii U [og]) mid-rendering?
