### ISSUE TITLE
make site url use dev branch

### ISSUE THREAD

**Issue by Rubiidev-IPad** [datkat21/mii-maker.ts#9]
yes, also i'm happy this update released!

**Comment by datkat21** [comment]
It's a work in progress to get everything pushed and worked on as I'm in the process of merging all these new changes and also the new local changes I've made too lol.

**Comment by datkat21** [comment]
It will be available on the site once I finish the merge with my local changes

**Comment by datkat21** [comment]
It's up on the site now, if it doesn't change try to clear your cache and try again.
